"""Contract types shared by every consumer of the connector.

This module sits at the bottom of the dependency graph: it imports nothing from
this package and nothing vendor-specific. An import of httpx, mcp, or a
Salesforce SDK appearing here means the layering has been broken.
"""

from collections.abc import Mapping
from enum import StrEnum
from typing import Annotated, Any, Protocol, Self

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator

# The program assigns dotted action IDs (salesforce.search_contact) and requires
# them verbatim. LLM providers reject dots in tool names, so a separate
# provider-safe name is carried alongside rather than rewriting either one.
ActionId = Annotated[str, StringConstraints(pattern=r"^[a-z0-9_]+\.[a-z0-9_]+$")]
ToolName = Annotated[str, StringConstraints(pattern=r"^[a-z0-9_]{1,64}$")]
ErrorCode = Annotated[str, StringConstraints(pattern=r"^[a-z0-9_.]+$")]


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class ActionKind(StrEnum):
    """Whether an action observes state or changes it."""

    READ = "read"
    WRITE = "write"


class RiskLevel(StrEnum):
    """How much damage an action does if it runs when it should not."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class IdempotencySupport(StrEnum):
    """How far this connector can honour a repeated call."""

    NONE = "none"
    WITH_KEY = "with_key"
    PROCESS_SCOPED = "process_scoped"


class ErrorCategory(StrEnum):
    """The four categories a model can act on.

    The category must be recoverable from the error text alone, because that
    text is all a language model ever sees.
    """

    TRANSIENT = "transient"  # wait, then retry the same call
    INPUT = "input"  # fix an argument, then retry
    RESOURCE = "resource"  # do not retry; report the condition
    FATAL = "fatal"  # stop and escalate to a human


class ActionError(_Frozen):
    """A failure described so its reader knows what to do next.

    Both `reason` and `next_step` are required so that an error carrying no
    remedy cannot be constructed.
    """

    code: ErrorCode
    category: ErrorCategory
    reason: str
    next_step: str
    retryable: bool = False
    retry_after_seconds: float | None = None
    invalid_fields: tuple[str, ...] = ()


class Pagination(_Frozen):
    """Where a paged result stopped and how to continue it.

    `next_cursor` is opaque and must be passed back unmodified.
    """

    returned: int
    has_more: bool
    next_cursor: str | None = None
    total_size: int | None = None


class RateLimit(_Frozen):
    """Provider quota as reported on the response that carried it."""

    used: int
    limit: int


class ActionResult(_Frozen):
    """The single envelope every action returns, success or failure."""

    ok: bool
    request_id: str
    data: Mapping[str, Any] = Field(default_factory=dict)
    error: ActionError | None = None
    pagination: Pagination | None = None
    rate_limit: RateLimit | None = None
    warnings: tuple[str, ...] = ()

    @model_validator(mode="after")
    def _outcome_must_be_consistent(self) -> Self:
        if self.ok and self.error is not None:
            raise ValueError("a successful result cannot carry an error")
        if not self.ok and self.error is None:
            raise ValueError("a failed result must carry an error")
        return self


class ActionRequest(_Frozen):
    """One call to one action.

    `idempotency_key` is generated by the calling loop, never by a model, and
    reused unchanged on every retry of the same logical operation.
    """

    action_id: ActionId
    params: Mapping[str, Any] = Field(default_factory=dict)
    idempotency_key: str | None = None
    approved: bool = False


class ActionDescriptor(_Frozen):
    """What a consumer needs to expose one action without reading its code."""

    action_id: ActionId
    tool_name: ToolName
    title: str
    description: str
    kind: ActionKind
    risk: RiskLevel
    idempotent: bool
    requires_approval: bool
    input_schema: Mapping[str, Any]
    output_schema: Mapping[str, Any]

    @model_validator(mode="after")
    def _high_risk_requires_approval(self) -> Self:
        if self.risk is RiskLevel.HIGH and not self.requires_approval:
            raise ValueError(f"{self.action_id}: high-risk actions must require approval")
        return self


class ConnectionTestResult(_Frozen):
    """Outcome of a credential check that changed nothing."""

    ok: bool
    api_version: str
    instance_url: str
    message: str


class Capabilities(_Frozen):
    """What this connector supports, declared rather than discovered."""

    pagination: bool
    rate_limit_metadata: bool
    idempotency: IdempotencySupport
    transports: tuple[str, ...]
    approval_required_for_writes: bool


class ConnectorManifest(_Frozen):
    """The connector's self-description, required by Definition of Done item 1."""

    provider: str
    version: str
    auth_type: str
    scopes: tuple[str, ...]
    actions: tuple[ActionId, ...]
    risks: tuple[str, ...]
    capabilities: Capabilities


class Credentials(Protocol):
    """Opaque credentials.

    This layer never sees the fields, only a rendering that is safe to log.
    """

    def redacted(self) -> str:
        """Return a form safe to write to a log."""
        ...


class DooConnector(Protocol):
    """The contract every connector in the program implements."""

    manifest: ConnectorManifest

    async def test_connection(self, credentials: Credentials) -> ConnectionTestResult:
        """Verify credentials without causing any side effect."""
        ...

    def list_actions(self) -> tuple[ActionDescriptor, ...]:
        """Return every action this connector exposes."""
        ...

    async def execute(self, request: ActionRequest) -> ActionResult:
        """Run one action and return the uniform envelope."""
        ...
